[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci --include=dev --legacy-peer-deps --ignore-scripts"]

[phases.build]
cmds = ["npx prisma generate", "npx next build"]

[start]
cmd = "npx prisma db push --accept-data-loss --skip-generate && npx prisma db seed && npm start"
