/**
 * POST /api/assignments/generate-key — the teacher uploads only the files; the
 * AI reads them and returns the answer key + detailed solutions (no manual key).
 *
 * Body: { skill: "READING" | "LISTENING", pdfUrl, audioUrl? }
 *   - pdfUrl : the đề-bài PDF **or .docx** as a data URL (or public URL).
 *   - audioUrl : REQUIRED for LISTENING (the answers come from the audio).
 *
 * READING is generated by CLAUDE reading the PDF natively (beta documents API):
 * huge context + high limits + works on scans, so it's far more reliable than
 * Groq's 12k-tokens/minute free tier (which 413s on a full passage). Groq is a
 * fallback (needs extracted text). LISTENING stays on Groq: its answers come
 * from the audio transcript (Deepgram) + the questions text.
 *
 * .docx: Claude's document API takes a PDF, not a Word file, so a .docx skips the
 * native branch and goes straight to text extraction (mammoth) → Groq. That is no
 * loss — a Word table is real text, so it extracts cleanly, unlike an image table
 * inside a PDF, which only Claude's native/vision path can read.
 */
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireTeacher } from "@/lib/teacher-auth";
import { detectDocKind, extractDocumentText } from "@/lib/doc-extract";
import { generatePaperKeyGroq, generateReadingExamGroq, numberReadingParts, type NumberedReadingPart } from "@/lib/groq";
import { generateReadingExamFromPdf } from "@/lib/claude";
import { deepgramTranscribe } from "@/lib/deepgram";
import { getApiKey } from "@/lib/api-keys";

// Claude reading a full multi-passage PDF + solving up to 40 questions with
// Vietnamese solutions can take a couple of minutes.
export const maxDuration = 300;

const bodySchema = z.object({
  skill: z.enum(["READING", "LISTENING"]),
  // Tên giữ nguyên `pdfUrl` để không phá client cũ; nay nhận cả .docx.
  pdfUrl: z.string().min(1, "Thiếu file đề (PDF hoặc .docx)"),
  audioUrl: z.string().optional(),
});

/** Decode `data:<mime>;base64,<data>` → { bytes, mime }; null if not a data URL. */
function decodeDataUrl(u: string): { bytes: ArrayBuffer; mime: string } | null {
  const comma = u.indexOf(",");
  if (!u.startsWith("data:") || comma === -1) return null;
  const header = u.slice(5, comma);
  const mime = header.split(";")[0] || "application/octet-stream";
  const buf = Buffer.from(u.slice(comma + 1), "base64");
  const bytes = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
  return { bytes, mime };
}

/** Get a PDF's base64 payload (no data: prefix) from a data URL or a public URL. */
async function pdfToBase64(pdfUrl: string): Promise<string | null> {
  if (pdfUrl.startsWith("data:")) {
    const comma = pdfUrl.indexOf(",");
    return comma === -1 ? null : pdfUrl.slice(comma + 1);
  }
  try {
    const r = await fetch(pdfUrl);
    if (!r.ok) return null;
    return Buffer.from(await r.arrayBuffer()).toString("base64");
  } catch {
    return null;
  }
}

function readingResponse(parts: NumberedReadingPart[], notes: string, engine: string, claudeReason = "") {
  const total = parts.reduce((n, p) => n + p.questions.length, 0);
  // Groq is the WEAK fallback (small context, truncates a full paper → misses the
  // later passages). If it ran, either the server has no ANTHROPIC_API_KEY OR the
  // Claude PDF path errored — surface WHICH, so we stop guessing why it's on Groq.
  const finalNotes =
    engine === "groq"
      ? `⚠ Đang dùng Groq (bản dự phòng, dễ thiếu câu vì không đọc trọn file).${claudeReason ? " Lý do không dùng được Claude: " + claudeReason + "." : ""} Hãy thêm/kiểm tra ANTHROPIC_API_KEY trên máy chủ để AI đọc trọn PDF và tách đủ các câu.${notes ? " " + notes : ""}`
      : notes;
  return NextResponse.json({
    mode: "reading",
    parts,
    notes: finalNotes,
    meta: { engine, partCount: parts.length, questionCount: total, claudeReason: claudeReason || undefined },
  });
}

export async function POST(req: Request) {
  const gate = await requireTeacher();
  if (gate instanceof NextResponse) return gate;

  const hasGroq = !!(await getApiKey("GROQ"));
  const hasClaude = !!(await getApiKey("ANTHROPIC"));
  if (!hasGroq && !hasClaude) {
    return NextResponse.json(
      { error: "Máy chủ chưa cấu hình khoá AI (ANTHROPIC_API_KEY hoặc GROQ_API_KEY). Hãy báo admin thêm khoá." },
      { status: 500 },
    );
  }

  const parsed = bodySchema.safeParse(await req.json().catch(() => ({})));
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message || "Dữ liệu không hợp lệ" },
      { status: 400 },
    );
  }
  const { skill, pdfUrl, audioUrl } = parsed.data;

  // ======================= READING =======================
  if (skill === "READING") {
    // PRIMARY: Claude reads the PDF natively (no pdf-parse, no token-limit,
    // handles scans). Falls back to Groq (needs extracted text) on any failure.
    // `claudeReason` records WHY we fell back so the teacher (and we) can tell a
    // missing key from a runtime error instead of guessing.
    let claudeReason = "";
    // Claude's document API expects a PDF. A .docx must skip the native branch.
    const isDocx = detectDocKind(pdfUrl) === "docx";
    if (isDocx) {
      claudeReason = "file .docx — Claude đọc PDF, nên dùng Groq đọc chữ trích từ Word";
    } else if (hasClaude) {
      const b64 = await pdfToBase64(pdfUrl);
      if (b64) {
        try {
          const multi = await generateReadingExamFromPdf(b64);
          const parts = numberReadingParts(multi);
          if (parts.some((p) => p.questions.length > 0)) return readingResponse(parts, multi.notes, "claude");
          claudeReason = "Claude đọc được file nhưng không tách ra được câu hỏi nào";
          console.warn("[generate-key] claude returned empty reading — falling back to groq");
        } catch (e) {
          claudeReason = `Claude gặp lỗi khi đọc PDF — ${e instanceof Error ? e.message.slice(0, 200) : String(e).slice(0, 200)}`;
          console.error("[generate-key] claude reading failed — falling back to groq:", e);
        }
      } else {
        claudeReason = "không đọc/giải mã được file PDF gửi lên";
      }
    } else {
      claudeReason = "máy chủ CHƯA cấu hình ANTHROPIC_API_KEY";
    }

    if (!hasGroq) {
      return NextResponse.json(
        { error: "AI tạo đề thất bại (Claude gặp lỗi, chưa có Groq dự phòng). Thử lại sau ít phút hoặc nhập đáp án thủ công." },
        { status: 502 },
      );
    }

    let documentText = "";
    try {
      documentText = await extractDocumentText(pdfUrl);
    } catch (e) {
      console.error("[generate-key] document extract failed:", e);
      return NextResponse.json(
        {
          error: `Máy chủ chưa đọc được nội dung file ${isDocx ? ".docx" : "PDF"}. Hãy thử lại; nếu vẫn lỗi hãy báo để kiểm tra.`,
          detail: e instanceof Error ? e.message.slice(0, 200) : String(e).slice(0, 200),
        },
        { status: 500 },
      );
    }
    if (documentText.replace(/\s+/g, " ").trim().length < 120) {
      return NextResponse.json(
        {
          error: isDocx
            ? "File .docx gần như không có chữ. Hãy kiểm tra lại file, hoặc nhập đáp án thủ công."
            : "PDF gần như không có chữ (có thể là ảnh scan). Thêm khoá Anthropic để Claude đọc được ảnh, hoặc nhập đáp án thủ công.",
          scanned: !isDocx,
        },
        { status: 422 },
      );
    }
    try {
      const multi = await generateReadingExamGroq({ documentText });
      const parts = numberReadingParts(multi);
      if (!parts.some((p) => p.questions.length > 0)) {
        // multi.notes now carries the REAL reason (bad key / rate limit / scan…) —
        // surface it in the error so the teacher sees WHY, not a generic message.
        const reason = (multi.notes || "").trim();
        return NextResponse.json(
          {
            error: reason
              ? `Không tạo được bài. ${reason}`
              : "AI chưa đọc được bài đọc hoặc câu hỏi. Hãy kiểm tra lại file hoặc nhập đáp án thủ công.",
            notes: multi.notes,
          },
          { status: 422 },
        );
      }
      return readingResponse(parts, multi.notes, "groq", claudeReason);
    } catch (e) {
      console.error("[generate-key] groq reading failed:", e);
      return NextResponse.json(
        {
          error: "AI tạo đề thất bại. Thử lại sau ít phút hoặc nhập đáp án thủ công.",
          detail: e instanceof Error ? e.message.slice(0, 200) : String(e).slice(0, 200),
        },
        { status: 502 },
      );
    }
  }

  // ======================= LISTENING =======================
  if (!hasGroq) {
    return NextResponse.json(
      { error: "Bài Listening cần khoá GROQ_API_KEY trên máy chủ. Hãy báo admin thêm khoá." },
      { status: 500 },
    );
  }
  if (!audioUrl || !audioUrl.trim()) {
    return NextResponse.json({ error: "Bài Listening cần file nghe để AI tạo đáp án." }, { status: 400 });
  }

  let documentText = "";
  try {
    documentText = await extractDocumentText(pdfUrl); // PDF hoặc .docx
  } catch (e) {
    console.error("[generate-key] document extract failed:", e);
    return NextResponse.json(
      {
        error: `Máy chủ chưa đọc được nội dung file ${detectDocKind(pdfUrl) === "docx" ? ".docx" : "PDF"}. Hãy thử lại; nếu vẫn lỗi hãy báo để kiểm tra.`,
        detail: e instanceof Error ? e.message.slice(0, 200) : String(e).slice(0, 200),
      },
      { status: 500 },
    );
  }

  let audioTranscript = "";
  try {
    let bytes: ArrayBuffer;
    let mime: string;
    if (audioUrl.startsWith("data:")) {
      const d = decodeDataUrl(audioUrl);
      if (!d) throw new Error("audio data URL không hợp lệ");
      bytes = d.bytes;
      mime = d.mime;
    } else {
      const r = await fetch(audioUrl);
      if (!r.ok) throw new Error(`fetch audio ${r.status}`);
      bytes = await r.arrayBuffer();
      mime = r.headers.get("content-type") || "audio/mpeg";
    }
    const tr = await deepgramTranscribe(bytes, mime);
    audioTranscript = tr.transcript.trim();
  } catch (e) {
    console.error("[generate-key] transcribe failed:", e);
    return NextResponse.json(
      { error: "Không nhận dạng được file nghe. Hãy thử lại hoặc nhập đáp án thủ công." },
      { status: 422 },
    );
  }

  if (documentText.replace(/\s+/g, " ").trim().length < 120 && !audioTranscript) {
    return NextResponse.json(
      { error: "PDF gần như không có chữ (có thể là ảnh scan). Hãy nhập đáp án thủ công.", scanned: true },
      { status: 422 },
    );
  }

  try {
    const result = await generatePaperKeyGroq({ skill, documentText, audioTranscript });
    if (result.questions.length === 0) {
      return NextResponse.json(
        { error: "AI chưa tìm thấy câu hỏi nào trong đề. Hãy kiểm tra lại file hoặc nhập đáp án thủ công.", notes: result.notes },
        { status: 422 },
      );
    }
    return NextResponse.json({
      mode: "listening",
      questions: result.questions,
      notes: result.notes,
      meta: { pdfChars: documentText.length, transcriptChars: audioTranscript.length },
    });
  } catch (e) {
    console.error("[generate-key] groq listening failed:", e);
    return NextResponse.json(
      {
        error: "AI tạo đáp án thất bại. Thử lại sau ít phút hoặc nhập đáp án thủ công.",
        detail: e instanceof Error ? e.message.slice(0, 200) : String(e).slice(0, 200),
      },
      { status: 502 },
    );
  }
}
